# Generated by Django 2.1.2 on 2018-10-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_course_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('FREE', 'Free'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=250)),
                ('price', models.IntegerField()),
                ('courses', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
