# Generated by Django 2.1.2 on 2018-10-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_usermembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.UUIDField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.Membership')),
                ('user_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.UserMembership')),
            ],
        ),
    ]
