# Generated by Django 2.1.2 on 2018-10-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='stripe_id',
            field=models.CharField(max_length=250),
        ),
    ]
