# Generated by Django 2.1.2 on 2018-10-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
