# Generated by Django 2.1.2 on 2018-11-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_membership_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='courses',
        ),
    ]
