# Generated by Django 2.1.2 on 2018-11-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_memberships'),
        ('memberships', '0007_remove_membership_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
