# Generated by Django 2.1.2 on 2018-10-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
